=== 2004JL/HDG_group/student_schemas.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Student",
  "type": "object",
  "additionalProperties": false,
  "required": ["id", "preferred_country"],
  "properties": {
    "id": {"type": "string"},
    "name": {"type": "string"},
    "age": {"type": "integer", "minimum": 17, "maximum": 35},
    "gender": {"type": "string", "enum": ["female","male"]},
    "nationality": {"type": "string"},
    "previous_degree": {"type": "string", "enum": ["Bachelor","Master","PhD","HighSchool"]},
    "gpa": {
      "description": "If high school, then GPA is N/A",
      "oneOf": [
        {"type": "string", "const": "N/A"},
        {"type": "number", "minimum": 0.0, "maximum": 7.0}
      ]
    },
    "highschool_grade_rank": {
      "description": "Use rank to unity the grade in different country",
      "oneOf": [
        {"type": "string", "const": "N/A"},
        {"type": "number", "minimum": 0.0, "maximum": 100.0}
      ]
    },
    "english_tests": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["type","score"],
        "properties": {
          "type": {"type": "string", "enum": ["IELTS","TOEFL","PTE"]},
          "score": {"type": "number", "minimum": 0}
        }
      }
    },
    "apply_major": {"type": "string"},
    "apply_degree": {"type": "string", "enum": ["Bachelor","Master","PhD"]},
    "purpose": {
      "type": "string", 
      "enum": [
        "Futher_education",
        "Career_advancement",
        "Migration_pathway",
        "Personal_interest",
        "Research_opportunities"
      ]
    },
    "interests_fields": {"type": "string"},
    "preferred_country": {"type": "string"},
    "study_budget": {"type": "number"},
    "migration_goal": {"type": "boolean"},
    "visa_type": {"type": "string", "enum": ["500","485"]}
  }
}

=== 2004JL/HDG_group/synthetic_students.json
[
  {
    "id": "STU0001",
    "name": "Student 1",
    "age": 25,
    "gender": "female",
    "nationality": "Brazil",
    "previous_degree": "Bachelor",
    "gpa": 4.08,
    "highschool_grade_rank": "N/A",
    "english_tests": [
      {
        "type": "TOEFL",
        "score": 115.0
      }
    ],
    "apply_major": "Mathematics",
    "apply_degree": "Master",
    "purpose": "Futher_education",
    "interests_fields": "AI/ML",
    "preferred_country": "Canada",
    "study_budget": 42500.0,
    "migration_goal": false,
    "visa_type": "500"
  },
  {
    "id": "STU0002",
    "name": "Student 2",
    "age": 34,
    "gender": "male",
    "nationality": "Brazil",
    "previous_degree": "Bachelor",
    "gpa": 6.15,
    "highschool_grade_rank": "N/A",
    "english_tests": [
      {
        "type": "PTE",
        "score": 78.0
      }
    ],
    "apply_major": "Business Analytics",
    "apply_degree": "Master",
    "purpose": "Personal_interest",
    "interests_fields": "Materials Science",
    "preferred_country": "New Zealand",
    "study_budget": 34500.0,
    "migration_goal": false,
    "visa_type": "485"
  },
  {
    "id": "STU0003",
    "name": "Student 3",
    "age": 28,
    "gender": "male",
    "nationality": "USA",
    "previous_degree": "HighSchool",
    "gpa": "N/A",
    "highschool_grade_rank": 38.0,
    "english_tests": [
      {
        "type": "PTE",
        "score": 64.0
      }
    ],
    "apply_major": "Civil Engineering",
    "apply_degree": "Bachelor",
    "purpose": "Personal_interest",
    "interests_fields": "Sustainability",
    "preferred_country": "New Zealand",
    "study_budget": 61000.0,
    "migration_goal": true,
    "visa_type": "500"
  },
  {
    "id": "STU0004",
    "name": "Student 4",
    "age": 24,
    "gender": "male",
    "nationality": "Singapore",
    "previous_degree": "Bachelor",
    "gpa": 4.14,
    "highschool_grade_rank": "N/A",
    "english_tests": [
      {
        "type": "PTE",
        "score": 47.0
      },
      {
        "type": "TOEFL",
        "score": 98.0
      }
    ],
    "apply_major": "Law",
    "apply_degree": "Master",
    "purpose": "Migration_pathway",
    "interests_fields": "Entrepreneurship",
    "preferred_country": "Ireland",
    "study_budget": 60000.0,
    "migration_goal": false,
    "visa_type": "485"
  },
  {
    "id": "STU0005",
    "name": "Student 5",
    "age": 19,
    "gender": "female",
    "nationality": "Italy",
    "previous_degree": "Bachelor",
    "gpa": 6.05,
    "highschool_grade_rank": "N/A",
    "english_tests": [
      {
        "type": "PTE",
        "score": 54.0
      },
      {
        "type": "TOEFL",
        "score": 74.0
      }
    ],
    "apply_major": "Law",
    "apply_degree": "Master",
    "purpose": "Research_opportunities",
    "interests_fields": "Human-Computer Interaction",
    "preferred_country": "Ireland",
    "study_budget": 22000.0,
    "migration_goal": false,
    "visa_type": "500"
  },
  {
    "id": "STU0006",
    "name": "Student 6",
    "age": 19,
    "gender": "female",
    "nationality": "Portugal",
    "previous_degree": "Master",
    "gpa": 5.8,
    "highschool_grade_rank": "N/A",
    "english_tests": [
      {
        "type": "PTE",
        "score": 71.0
      },
      {
        "type": "IELTS",
        "score": 6.7
      }
    ],
    "apply_major": "Law",
    "apply_degree": "PhD",
    "purpose": "Personal_interest",
    "interests_fields": "FinTech",
    "preferred_country": "New Zealand",
    "study_budget": 32500.0,
    "migration_goal": false,
    "visa_type": "485"
  },
  {
    "id": "STU0007",
    "name": "Student 7",
    "age": 35,
    "gender": "male",
    "nationality": "Egypt",
    "previous_degree": "Bachelor",
    "gpa": 5.29,
    "highschool_grade_rank": "N/A",
    "english_tests": [
      {
        "type": "PTE",
        "score": 35.0
      }
    ],
    "apply_major": "Information Systems",
    "apply_degree": "Master",
    "purpose": "Futher_education",
    "interests_fields": "Healthcare",
    "preferred_country": "United Kingdom",
    "study_budget": 35000.0,
    "migration_goal": true,
    "visa_type": "485"
  },
  {
    "id": "STU0008",
    "name": "Student 8",
    "age": 31,
    "gender": "male",
    "nationality": "Spain",
    "previous_degree": "Bachelor",
    "gpa": 5.15,
    "highschool_grade_rank": "N/A",
    "english_tests": [
      {
        "type": "TOEFL",
        "score": 108.0
      },
      {
        "type": "PTE",
        "score": 78.0
      }
    ],
    "apply_major": "Marketing",
    "apply_degree": "Master",
    "purpose": "Migration_pathway",
    "interests_fields": "Healthcare",
    "preferred_country": "New Zealand",
    "study_budget": 70500.0,
    "migration_goal": false,
    "visa_type": "485"
  },
  {
    "id": "STU0009",
    "name": "Student 9",
    "age": 25,
    "gender": "female",
    "nationality": "Germany",
    "previous_degree": "HighSchool",
    "gpa": "N/A",
    "highschool_grade_rank": 72.2,
    "english_tests": [
      {
        "type": "IELTS",
        "score": 8.3
      },
      {
        "type": "TOEFL",
        "score": 104.0
      }
    ],
    "apply_major": "Education",
    "apply_degree": "Bachelor",
    "purpose": "Career_advancement",
    "interests_fields": "FinTech",
    "preferred_country": "Ireland",
    "study_budget": 35500.0,
    "migration_goal": true,
    "visa_type": "500"
  },
  {
    "id": "STU0010",
    "name": "Student 10",
    "age": 20,
    "gender": "male",
    "nationality": "Argentina",
    "previous_degree": "Bachelor",
    "gpa": 5.47,
    "highschool_grade_rank": "N/A",
    "english_tests": [
      {
        "type": "TOEFL",
        "score": 50.0
      }
    ],
    "apply_major": "Linguistics",
    "apply_degree": "Master",
    "purpose": "Personal_interest",
    "interests_fields": "Sustainability",
    "preferred_country": "United Kingdom",
    "study_budget": 31000.0,
    "migration_goal": true,
    "visa_type": "485"
  },
  {
    "id": "STU0011",
    "name": "Student 11",
    "age": 33,
    "gender": "male",
    "nationality": "Japan",
    "previous_degree": "Master",
    "gpa": 5.33,
    "highschool_grade_rank": "N/A",
    "english_tests": [
      {
        "type": "TOEFL",
        "score": 79.0
      },
      {
        "type": "IELTS",
        "score": 6.3
      }
    ],
    "apply_major": "Sociology",
    "apply_degree": "PhD",
    "purpose": "Migration_pathway",
    "interests_fields": "Digital Marketing",
    "preferred_country": "Netherlands",
    "study_budget": 30000.0,
    "migration_goal": false,
    "visa_type": "500"
  },
  {
    "id": "STU0012",
    "name": "Student 12",
    "age": 34,
    "gender": "female",
    "nationality": "UK",
    "previous_degree": "HighSchool",
    "gpa": "N/A",
    "highschool_grade_rank": 2.1,
    "english_tests": [
      {
        "type": "TOEFL",
        "score": 69.0
      }
    ],
    "apply_major": "Mechanical Engineering",
    "apply_degree": "Bachelor",
    "purpose": "Futher_education",
    "interests_fields": "Materials Science",
    "preferred_country": "Canada",
    "study_budget": 80500.0,
    "migration_goal": false,
    "visa_type": "485"
  },
  {
    "id": "STU0013",
    "name": "Student 13",
    "age": 21,
    "gender": "male",
    "nationality": "Mexico",
    "previous_degree": "Bachelor",
    "gpa": 4.64,
    "highschool_grade_rank": "N/A",
    "english_tests": [
      {
        "type": "PTE",
        "score": 36.0
      },
      {
        "type": "IELTS",
        "score": 4.9
      }
    ],
    "apply_major": "Mathematics",
    "apply_degree": "Master",
    "purpose": "Migration_pathway",
    "interests_fields": "Cloud Computing",
    "preferred_country": "Germany",
    "study_budget": 74500.0,
    "migration_goal": true,
    "visa_type": "500"
  },
  {
    "id": "STU0014",
    "name": "Student 14",
    "age": 20,
    "gender": "female",
    "nationality": "Saudi Arabia",
    "previous_degree": "Bachelor",
    "gpa": 6.95,
    "highschool_grade_rank": "N/A",
    "english_tests": [
      {
        "type": "TOEFL",
        "score": 64.0
      },
      {
        "type": "PTE",
        "score": 42.0
      }
    ],
    "apply_major": "Environmental Science",
    "apply_degree": "Master",
    "purpose": "Personal_interest",
    "interests_fields": "FinTech",
    "preferred_country": "Germany",
    "study_budget": 38000.0,
    "migration_goal": false,
    "visa_type": "485"
  },
  {
    "id": "STU0015",
    "name": "Student 15",
    "age": 31,
    "gender": "female",
    "nationality": "Indonesia",
    "previous_degree": "HighSchool",
    "gpa": "N/A",
    "highschool_grade_rank": 92.3,
    "english_tests": [
      {
        "type": "TOEFL",
        "score": 51.0
      },
      {
        "type": "IELTS",
        "score": 8.7
      }
    ],
    "apply_major": "Accounting",
    "apply_degree": "Bachelor",
    "purpose": "Career_advancement",
    "interests_fields": "Cloud Computing",
    "preferred_country": "Netherlands",
    "study_budget": 76500.0,
    "migration_goal": false,
    "visa_type": "485"
  },
  {
    "id": "STU0016",
    "name": "Student 16",
    "age": 17,
    "gender": "male",
    "nationality": "Colombia",
    "previous_degree": "Master",
    "gpa": 5.33,
    "highschool_grade_rank": "N/A",
    "english_tests": [
      {
        "type": "IELTS",
        "score": 6.4
      },
      {
        "type": "PTE",
        "score": 76.0
      }
    ],
    "apply_major": "Environmental Science",
    "apply_degree": "PhD",
    "purpose": "Personal_interest",
    "interests_fields": "FinTech",
    "preferred_country": "United States",
    "study_budget": 52500.0,
    "migration_goal": false,
    "visa_type": "500"
  },
  {
    "id": "STU0017",
    "name": "Student 17",
    "age": 27,
    "gender": "female",
    "nationality": "Indonesia",
    "previous_degree": "Bachelor",
    "gpa": 5.63,
    "highschool_grade_rank": "N/A",
    "english_tests": [
      {
        "type": "TOEFL",
        "score": 47.0
      }
    ],
